### ISSUE TITLE
Can't we simplify?

### ISSUE THREAD

**Issue by ninjasort** [simbo/metalsmith-better-excerpts#1]
So firstly thanks for this, but was there a reason to create a whole new plugin when this already exists? PR's are cool too. Thoughts on merging this functionality into https://github.com/segmentio/metalsmith-excerpts ?

**Comment by simbo** [comment]
I got the impression, that the people at segment are not really focused on improving metalsmith plugins or merging pull requests. Just take a look at open pull requests at [metalsmith-excerpts](https://github.com/segmentio/metalsmith-excerpts/pulls) or [metalsmith-permalinks](https://github.com/segmentio/metalsmith-permalinks/pulls) (there is also an open pr of my own).

I would like to see the functionality of metalsmith-better-excerpts in metalsmith-excerpts, but i don't want to waste any energy in creating pull requests that will never be merged. That's why i ended up with my own excerpt plugin. I'm tired of linking forks in my package.json, because people are lazy on PRs...

But hey, this is open source. Feel free to create a pull request for metalsmith-excerpts...
